name: flutter_firebase_tdd_clean_architecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # equatable: helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.5

  # dartz: Functional Programming in Dart. Purifies Dart code using efficient immutable data structures, monads, lenses and other FP tools.
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # simplifies mocking with null safety support and no manual mocks or code generation
  mocktail: ^1.0.2

flutter:
  uses-material-design: true
